name: Stop Bunnyshell Environment
on:
  workflow_call:
    inputs:
      runs-on:
        description: The Platform to execute on
        type: string
        default: ubuntu-latest
      project-id:
        description: The Bunnyshell Project to use
        required: true
        type: string
      env-id:
        description: The ID of the Environment to stop
        type: string
      pr-number:
        description: The number of the PR on which to write the comments
        type: string
        required: false
      allowed-users:
        description: The list of the allowed usernames (JSON list). Use '*' for all users.
        type: string
      comment-on-pr:
        description: Write PR comments
        type: boolean
        default: false
      bunnyshell-cli-version:
        description: The version of the Bunnyshell CLI to use
        type: string
        default: v0.18.0
    secrets:
      bunnyshell-access-token:
        required: true
    outputs:
      env-id:
        description: The ID of the Environment
        value: ${{ jobs.stop.outputs.env-id }}
permissions:
  pull-requests: write
jobs:
  validations:
    name: Validate inputs
    if: ${{ github.event_name != 'issue_comment' || (
          github.event.issue.pull_request
          && contains(github.event.comment.body, '/bns:stop')
          && (inputs.allowed-users == '*'
            || contains(fromJSON(inputs.allowed-users), github.event.sender.login)
            || github.event.issue.user.login == github.event.sender.login
          )
        )
      }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Validate env ID or PR number
        if: "${{ inputs.env-id == '' && inputs.pr-number == '' }}"
        run: |
          echo "One of env-id or pr-number inputs is required."
          exit 1
  stop:
    name: Stop Environment
    runs-on: ${{ inputs.runs-on }}
    outputs:
      env-id: ${{ inputs.env-id || env.BNS_ENV_ID }}
    needs: validations
    steps:
    - name: Search for Environment
      uses: addnab/docker-run-action@v3
      if: ${{ inputs.pr-number != '' }}
      with:
        image: bunnyshell/cli:${{ inputs.bunnyshell-cli-version }}
        options: -e BUNNYSHELL_TOKEN=${{ secrets.bunnyshell-access-token }} -v ${{ github.env }}:/github/envs.txt
        run: |
          set -e

          BNS_ENV_ID=`bns environments list --label "auto-gha=pr-${{ inputs.pr-number }}" --project ${{ inputs.project-id }} --non-interactive -o json \
            | jq -r "try ._embedded.item[0].id | select (.!=null)"`
          
          if [ -z "$BNS_ENV_ID" ]; then
            echo "Could not find environment with label 'auto-gha=pr-${{ inputs.pr-number }}'."

            exit 1
          fi
          
          echo "BNS_ENV_ID=$BNS_ENV_ID" >> /github/envs.txt
    - name: Stop Environment
      uses: addnab/docker-run-action@v3
      with:
        image: bunnyshell/cli:${{ inputs.bunnyshell-cli-version }}
        options: >
          -e BUNNYSHELL_TOKEN=${{ secrets.bunnyshell-access-token }}
          -e BUNNYSHELL_ENVIRONMENT=${{ inputs.env-id || env.BNS_ENV_ID }}
        run: |
          ENV_OPERATION_STATUS=`bns environments show --non-interactive -o json | jq -r '.operationStatus'`
          if [ "$ENV_OPERATION_STATUS" != "stopped" ] && [ "$ENV_OPERATION_STATUS" != "running" ]; then
            echo "ERROR_MESSAGE=The Environment cannot be stopped right now. The current operation status is '$ENV_OPERATION_STATUS'." >> /github/envs.txt

            echo "The Environment cannot be stopped right now. The current operation status is '$ENV_OPERATION_STATUS'."
            exit 1
          fi

          if [ "$ENV_OPERATION_STATUS" != "stopped" ]; then
            bns environments stop --non-interactive -o stylish
          else
            echo "The environment is already stopped."
          fi
    - name: Comment PR Environment stopped
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ inputs.comment-on-pr }}
      with:
        message: |
          ### [Bunnyshell](https://www.bunnyshell.com) Preview Environment stopped

          Available commands:
            - `/bns:start` to start the environment
            - `/bns:deploy` to redeploy the environment
            - `/bns:delete` to remove the environment
        comment_tag: bunnyshell-preview-env
    - name: Comment PR Environment stopping failed
      if: ${{ failure() && inputs.comment-on-pr }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ### [Bunnyshell](https://www.bunnyshell.com) Preview Environment stopping failed
          
          ${{ env.ERROR_MESSAGE }}

          Check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} for details.
          
          Available commands:
          - `/bns:stop` to stop the environment
          - `/bns:deploy` to redeploy the environment
          - `/bns:delete` to remove the environment
        comment_tag: bunnyshell-preview-env
