name: Stop Bunnyshell Environment
on:
  workflow_call:
    inputs:
      runs-on:
        description: The Platform to execute on
        type: string
        default: ubuntu-latest
      project-id:
        description: The Bunnyshell Project to use
        required: true
        type: string
      env-id:
        description: The ID of the Environment to stop
        type: string
      pr-number:
        description: The number of the PR on which to write the comments
        type: string
        required: false
      allowed-users:
        description: The list of the allowed usernames (JSON list). Use '*' for all users.
        type: string
      comment-on-pr:
        description: Write PR comments
        type: boolean
        default: false
      bunnyshell-cli-version:
        description: The version of the Bunnyshell CLI to use
        type: string
        default: v0.18.2
      env-label:
        description: The label prefix for automatic GitHub Actions
        type: string
        default: auto-gha
    secrets:
      bunnyshell-access-token:
        required: true
    outputs:
      env-id:
        description: The ID of the Environment
        value: ${{ jobs.stop.outputs.env-id }}
permissions:
  pull-requests: write
jobs:
  validations:
    name: Validate inputs
    if: ${{ github.event_name != 'issue_comment' || (
          github.event.issue.pull_request
          && contains(github.event.comment.body, '/bns:stop')
          && (inputs.allowed-users == '*'
            || contains(fromJSON(inputs.allowed-users), github.event.sender.login)
            || github.event.issue.user.login == github.event.sender.login
          )
        )
      }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Validate env ID or PR number
        if: "${{ inputs.env-id == '' && inputs.pr-number == '' }}"
        run: |
          echo "One of env-id or pr-number inputs is required."
          exit 1
  stop:
    name: Stop Environment
    runs-on: ${{ inputs.runs-on }}
    outputs:
      env-id: ${{ inputs.env-id || env.BNS_ENV_ID }}
    needs: validations
    steps:
    - name: Search for Environment
      uses: addnab/docker-run-action@v3
      if: ${{ inputs.pr-number != '' }}
      with:
        image: bunnyshell/cli:${{ inputs.bunnyshell-cli-version }}
        options: >
          -e BUNNYSHELL_TOKEN=${{ secrets.bunnyshell-access-token }}
          -v ${{ github.env }}:/github/envs.txt
          -v ${{ github.step_summary }}:/github/step_summary.txt
        run: |
          set -e

          BNS_ENV_ID=`bns environments list --label "${{ inputs.env-label }}=pr-${{ inputs.pr-number }}" --project ${{ inputs.project-id }} --non-interactive -o json \
            | jq -r "try ._embedded.item[0].id | select (.!=null)"`
          
          if [ -z "$BNS_ENV_ID" ]; then
            echo "No environment exists with label '${{ inputs.env-label }}=pr-${{ inputs.pr-number }}'."
            echo ":exclamation: No environment exists with label '${{ inputs.env-label }}=pr-${{ inputs.pr-number }}'." >> /github/step_summary.txt
          
            exit 1
          else
              echo "Found environment ID $BNS_ENV_ID"
              echo ":mag: Found environment ID $BNS_ENV_ID." >> /github/step_summary.txt
          fi
          
          echo "BNS_ENV_ID=$BNS_ENV_ID" >> /github/envs.txt
    - name: Stop Environment
      uses: addnab/docker-run-action@v3
      with:
        image: bunnyshell/cli:${{ inputs.bunnyshell-cli-version }}
        options: >
          -e BUNNYSHELL_TOKEN=${{ secrets.bunnyshell-access-token }}
          -e BUNNYSHELL_ENVIRONMENT=${{ inputs.env-id || env.BNS_ENV_ID }}
          -v ${{ github.env }}:/github/envs.txt
          -v ${{ github.step_summary }}:/github/step_summary.txt
        run: |
          ENV_OPERATION_STATUS=`bns environments show --non-interactive -o json | jq -r '.operationStatus'`
          if [ "$ENV_OPERATION_STATUS" != "stopped" ] && [ "$ENV_OPERATION_STATUS" != "running" ]; then
            echo "ERROR_MESSAGE=The Environment cannot be stopped right now. The current operation status is '$ENV_OPERATION_STATUS'." >> /github/envs.txt

            echo "The Environment cannot be stopped right now. The current operation status is '$ENV_OPERATION_STATUS'."
            echo ":exclamation: The Environment cannot be stopped right now. The current operation status is '$ENV_OPERATION_STATUS'." >> /github/step_summary.txt
            
            exit 1
          fi

          if [ "$ENV_OPERATION_STATUS" != "stopped" ]; then
            bns environments stop --non-interactive -o stylish
          
            if [ $? -eq 0 ]; then
              echo "The environment was successfully stopped."
              echo ":white_check_mark: The environment was successfully stopped." >> /github/step_summary.txt
            else
              echo "The environment was not stopped."
              echo ":exclamation: The environment was not stopped." >> /github/step_summary.txt
          
              exit 1
            fi
          else
            echo "The environment was already stopped."
            echo ":white_check_mark: The environment was already stopped." >> /github/step_summary.txt
          fi
    - name: Comment with PR Environment stopped
      uses: thollander/actions-comment-pull-request@v2
      if: ${{ inputs.comment-on-pr }}
      with:
        message: |
          ### :red_circle: Preview Environment stopped on [Bunnyshell](https://www.bunnyshell.com)
          
          See: [Environment Details](https://environments.bunnyshell.com/b/environment/${{ env.BNS_ENV_ID }})

          Available commands:
            - :large_blue_circle: `/bns:start` to start the environment
            - :rocket: `/bns:deploy` to redeploy the environment
            - :x: `/bns:delete` to remove the environment
        comment_tag: bunnyshell-preview-env
    - name: Comment PR with Environment stopping failed
      if: ${{ failure() && inputs.comment-on-pr }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ### :exclamation: Preview Environment stop on [Bunnyshell](https://www.bunnyshell.com) failed
          
          ${{ env.ERROR_MESSAGE }}

          Check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} for details.
          
          See: [Environment Details](https://environments.bunnyshell.com/b/environment/${{ env.BNS_ENV_ID }})
          
          Available commands:
          - :red_circle: `/bns:stop` to stop again the environment
          - :rocket: `/bns:deploy` to redeploy the environment
          - :x: `/bns:delete` to remove the environment
        comment_tag: bunnyshell-preview-env
